---

kind: pipeline
name: lint
platform:
  arch: amd64

steps:
  - name: lint
    image: golangci/golangci-lint
    commands:
      - make lint

---

kind: pipeline
name: test
platform:
  arch: amd64

steps:
  - name: test
    image: golang:alpine
    commands:
      - apk add make
      - make test

---

kind: pipeline
name: build
platform:
  arch: amd64

steps:
  - name: build
    image: golang:alpine
    commands:
      - apk add make
      - make build