---

kind: pipeline
name: lint

steps:
  - name: lint
    image: golangci/golangci-lint
    commands:
      - make lint

  - name: lint-markdown
    image: python:3-alpine
    commands:
      - apk add make
      - pip install mdformat-gfm
      - make lint-markdown

---

kind: pipeline
name: test

steps:
  - name: test
    image: golang:alpine
    commands:
      - apk add make
      - make test

---

kind: pipeline
name: build

steps:
  - name: build
    image: golang:alpine
    commands:
      - apk add make
      - make build
